# Generated by Django 4.0.4 on 2022-06-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_article_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
