# Generated by Django 4.0.4 on 2022-06-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_article_text_alter_comment_subcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='blogapp.comment'),
        ),
    ]
