# Generated by Django 4.0.4 on 2022-06-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_comment_subcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='like',
            field=models.BooleanField(),
        ),
    ]
