# Generated by Django 4.0.4 on 2022-06-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_rating_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='like',
        ),
        migrations.AddField(
            model_name='rating',
            name='choice',
            field=models.CharField(choices=[(1, 'Like'), (2, 'Dislike')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
