# Generated by Django 4.0.4 on 2022-06-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_remove_rating_dislike_remove_rating_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blogapp.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.article'),
        ),
    ]
