# Generated by Django 4.0.4 on 2022-06-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_rating_article_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogapp.comment'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.article'),
        ),
    ]
