# Generated by Django 4.0.4 on 2022-06-13 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='blogapp.comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='blogapp.person'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='choice',
            field=models.IntegerField(choices=[(1, 'Like'), (2, 'Dislike')]),
        ),
    ]
