# Generated by Django 4.0.4 on 2022-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_authorinlib_booksinlib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksinlib',
            name='authors',
        ),
        migrations.AddField(
            model_name='booksinlib',
            name='authors',
            field=models.ManyToManyField(to='myapp.authorinlib'),
        ),
    ]
